# SITE CONFIGURATION
title: Mary McTarsney # your site title
author: Mary McTarsney # You :P
description: # Meta description of Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmct1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://www.linkedin.com/in/mary-mctarsney/
    - https://github.com/mmct1
    - https://docs.google.com/document/d/e/2PACX-1vQII-nYj00hEHNrUNOnunUF0IiC4u2OSLvhfdgi96G-QKjBcl6RNjSEUoYQxt84vpZavqoBLrsb8U6F/pub?embedded=true


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
#  - {name: 'Contact', link: '/contact'}

tagline: >
  Data Science Fellow @ Cuny Tech Prep, Cohort 11

hero_img: posts/header_img_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

#email: your-email@domain.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
linkedin_username: mary-mctarsney
github_username:  mmct1 # replace with your_github_username or comment to remove link from footer
resume_username: mary
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
